version: '3.8'

name: "crs_system"
services:
  crs_app:
    build:
      context: ..\.
      dockerfile: Dockerfile
    container_name: crs_app
    restart: always
    ports:
      - "4100:4100"

networks:
  default:
    name: "shared-network"
